### PR TITLE
Patch/362

### LINKED ISSUE #362: LongestAliphaticChainDescriptor doesn't work
Personal communication from Nichola McCann

> I am relatively new to using the cdk, but I have a question about the descriptor generation. When I calculate the Longest Aliphatic Chain (nAtomLAC) for ethanol, I get different answers, depending on how I enter the molecule. If I use CCO, I get a value of 2, but if I use OCC (the canonical version from cdk), I get 0.
> I have attached below the R code that I used to generate these results – could you please explain the discrepancy?

```java
    @Test
    public void debug() throws ClassNotFoundException, CDKException, java.lang.Exception {
        SmilesParser sp = new SmilesParser(SilentChemObjectBuilder.getInstance());
        IAtomContainer mol1 = sp.parseSmiles("CCO");
        IAtomContainer mol2 = sp.parseSmiles("OCC");
        System.out.println(descriptor.calculate(mol1).getValue());
        System.out.println(descriptor.calculate(mol2).getValue());
    }
```

### PR DESCRIPTION
**Pull request by johnmay**
Resolve #362 and significantly clean up code.

### CODE REVIEW

File: descriptor/qsarmolecular/src/main/java/org/openscience/cdk/qsar/descriptors/molecular/LongestAliphaticChainDescriptor.java [hunk 1]
```diff
@@ -18,71 +18,67 @@
...
+ * @author John Mayfield
  * @cdk.created 2006-1-03
- * @cdk.module  qsarmolecular
+ * @cdk.module qsarmolecular
  * @cdk.githash
  * @cdk.dictref qsar-descriptors:largestAliphaticChain
  */
-public class LongestAliphaticChainDescriptor extends AbstractMolecularDescriptor implements IMolecularDescriptor {
+public class LongestAliphaticChainDescriptor
+    extends AbstractMolecularDescriptor {
```
Comment (egonw) [inline descriptor/qsarmolecular/src/main/java/org/openscience/cdk/qsar/descriptors/molecular/LongestAliphaticChainDescriptor.java]: Ah, does it make this class also "implement" what the abstract class implements? I did not know that...

Comment (johnmay) [reply descriptor/qsarmolecular/src/main/java/org/openscience/cdk/qsar/descriptors/molecular/LongestAliphaticChainDescriptor.java]: Of course
